[package]
name = "cdna-browser"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cdna-inference = { path = "../cdna-inference" }
serde = { version = "1", features = ["derive"] }
cdna-domain = { path = "../cdna-domain" }
serde_json = "1"
wasm-bindgen = "=0.2.128"
uuid = { version = "1", features = ["js"] }
