const staticMode = import.meta.env?.VITE_CDNA_STATIC === "true";
export const ja = {
  finish: "セッションを終える",
  navigation: "ナビゲーションを開閉",
  brand: "C-DNA",
  tagline: "判断を、育てる。",
  local: staticMode ? "このブラウザ内だけで処理" : "この端末だけで処理",
  demo: staticMode ? "ブラウザ体験版・一時データ" : "デモ保管庫",
  unverified: "個人精度は未検証",
  none: "実行権限なし",
  loading: "読み込み中…",
  refresh: "再読み込み",
  workspace: "ワークスペース",
  create: "新しく作成",
  workspaceName: "ワークスペース名",
  start: "最初の判断を記録する",
  welcome: "あなたの判断が、次の判断の手がかりになる。",
  welcomeBody:
    "選んだ理由と、考えが変わる条件を少しずつ残します。本人が確認した記録だけが学習の対象です。まずは架空の事例を1問、試してみましょう。",
  seed: "架空の問いを開く",
  confirmed: "本人確認済み",
  pending: "確認待ち",
  save: "回答を保存する",
  confirm: "本人の回答として確定",
  revise: "訂正する",
  remove: "削除する",
  cancel: "キャンセル",
  deleting: "削除を確定",
  deleteHelp: "この記録を削除すると、参照する候補モデルも無効化されます。",
  saved: "記録を保存しました。判断の記憶から本人確認できます。",
  confirmedMessage: "本人確認を保存しました。",
  revised: "新しいリビジョンとして保存しました。再度、本人確認してください。",
  draft: "未保存の下書き",
  notes: "選んだ理由・備考",
  reversal: "判断が逆転する条件",
  notesPlaceholder: "大切にしたこと、迷ったことを自分の言葉で。",
  reversalPlaceholder: "例：納期に余裕があれば、自社で開発する。",
  hypothetical: "架空の事例",
  actual: "実際の事例",
  purpose: "目的",
  constraints: "制約",
  background: "判断の背景",
  candidates: "候補",
  edit: "背景・候補を編集",
  unknown: "不明な情報",
  unknownHelp: "英小文字の項目名をカンマ区切りで入力（例：budget, deadline）",
  attributes: "数値属性（0〜1の相対値）",
  choice: "四択",
  pairwise: "二案比較",
  acceptability: "単一案の許容性",
  left: "左案を選ぶ",
  right: "右案を選ぶ",
  accept: "採用できる",
  reject: "採用しない",
  insufficient: "情報不足",
  noneFit: "どれも違う",
  tie: "同程度",
  skip: "スキップ",
  undo: "選択を取り消す",
  selected: "選択中",
  next: "別の問い",
  training: "学習中…",
  train: "確認済みの記録から学習",
  trainHelp: staticMode
    ? "同じ学習器をブラウザ内で実行します。初回はランタイムの取得に時間がかかります。独立した評価が不足している間は正式適用されません。"
    : "ローカルの学習エンジンで候補モデルを作ります。独立した評価が不足している間は正式適用されません。",
  provisional: "候補モデル・未承認",
  preview: "候補モデルで試す",
  previewHelp:
    "未承認モデルの試用です。結果を見た後の回答は学習対象から除外されます。スコアは確率ではありません。",
  rank: "確認済みの記憶を照合",
  rankHelp:
    "同じ背景・候補の本人確認済み記録と照合します。材料が足りなければ保留します。",
  held: "判断を保留しています",
  matched: "確認済みの判断が見つかりました",
  evidence: "参照した記録",
  score: "生スコア（確率ではありません）",
  noMemory: "まだ判断の記憶がありません",
  noMemoryBody: "架空の問いに回答して、理由と一緒に保存しましょう。",
  noModel: "候補モデルはまだありません",
  noModelBody: "まず回答を保存し、判断の記憶で本人確認してください。",
  search: "背景・備考を検索",
  all: "すべて",
  noResults: "該当する記録はありません",
  back: "戻る",
  status: "状態",
  source: "出典",
  human: "本人の入力",
  modelExposure: "モデル結果を閲覧済み",
  noExposure: "モデル結果の影響なし",
  mapHelp: "記録数は参加実績です。予測精度や経営能力を示すものではありません。",
  recorded: "記録あり・未検証",
  unlearned: "未学習",
  unavailable: "この機能はまだ利用できません",
  unavailableBody:
    "現時点では保存・適用できません。操作が成功したようには表示しません。",
  theme: "表示テーマを切り替え",
  privacy: staticMode
    ? "架空の事例をブラウザのメモリ内だけで処理します。ページを閉じる・再読み込みすると記録は消えます。学習ランタイムの読み込み以外に回答を外部へ送信しません。実際の個人情報や機密情報は入力しないでください。"
    : "記録はローカルの暗号化保管庫へ保存されます。外部送信は無効です。",
  export: "記録をJSONLで書き出す",
  lock: "保管庫をロック",
  locked: "保管庫をロックしました",
  lockedBody: staticMode
    ? "ブラウザ内の一時データを破棄しました。再開するにはページを再読み込みしてください。"
    : "再開するにはアプリを起動し直し、新しい専用URLを開いてください。",
  pagination: "次の100件",
  previous: "前の100件",
  noConnection: "ローカルアプリに接続してください",
  reconnect:
    "起動時に表示された専用URLを開いてください。セッション情報は端末へ保存しません。",
  count: "件",
  revision: "リビジョン",
  modelWarning: "候補モデルは正式適用できません。独立評価と承認が必要です。",
  keyboard: "1–4 選択 · Enter 確定 · N 備考 · ⌘/Ctrl Z 選択取消",
  compareKeyboard: "← 左案 / 不採用 · → 右案 / 採用",
  nowQuestion: "今日の問い",
  homeDescription: "判断を記録し、理由を確認し、少しずつ育てる。",
  trainingDescription: "自分ならどう決めるか。正解を探す必要はありません。",
  memoryDescription: "確定した判断も、後から理由と一緒に訂正できます。",
  judgmentDescription: "記憶との照合と、未承認モデルの試用を分けて確認します。",
  modelsDescription: "学習の成果と、まだ分からないことを確かめる。",
  mapDescription: "領域ごとの記録と検証の現在地。",
  ready: "接続済み",
  firstStep: "01 / 記録する",
  secondStep: "02 / 本人確認",
  thirdStep: "03 / 学習する",
  inputOffset: "入力元UTCオフセット",
  noAccuracy: "独立評価が不足しています。精度は未検証です。",
  rawEvaluation: "評価結果の詳細",
  epoch: "学習元の記録",
  newWorkspace: "新しいワークスペース",
  session: "今回のセッション",
  one: "1問",
  three: "3問",
  free: "任意数",
  completed: "今回の保存数",
  immediate: "選択時に保存する（即時回答）",
  immediateHelp:
    "保存後も判断の記憶から訂正・削除できます。本人確認は別の操作です。",
  noFields: "追加の不明項目なし",
  selectionRequired: "候補または補助回答を選んでください。",
  wait: "処理中…",
  proposalNotice: "本人確認前の記録は学習に使われません。",
  sourceId: "出典ID",
  sourceTime: "記録日時",
  connectionBody:
    "MCP接続には端末上で発行するスコープ付き資格情報が必要です。ブラウザのセッションは外部エージェントへ渡さないでください。",
  policiesBody:
    "判断方針の承認・期限・競合管理は未実装です。記録の備考を承認済み方針として扱いません。",
  personalityBody:
    "性格傾向の尺度は未設定です。回答から診断結果を推測しません。",
  previewEmpty: "候補モデルを作成してから試用できます。",
  timestamp: "日時表示",
  localTime: "端末のタイムゾーン",
  utc: "UTC",
  readonly: "保存後の内容は判断の記憶から訂正してください。",
  closeEdit: "編集を閉じる",
  selection: "回答",
  selectDomain: "判断の領域",
  fact: "背景の相対値",
  sourceNote: "教材の背景・属性は仮定です。実際の経営データではありません。",
} as const;
export const nav = {
  home: "ホーム",
  grow: "育てる",
  judge: "判断する",
  memory: "判断の記憶",
  policies: "判断方針",
  map: "学習マップ",
  models: "モデルと改善",
  connections: "接続",
  personality: "性格傾向",
  privacy: "プライバシー",
};
export type Page = keyof typeof nav;
export const domains: Record<string, string> = {
  resource_allocation: "資源配分",
  product_delivery: "開発・提供",
  customer_commercial: "顧客・取引",
  organization_delegation: "組織・委任",
  growth_strategy: "成長戦略",
  risk_reputation: "リスク・信頼",
};
export const attributes: Record<string, string> = {
  cost: "費用",
  effort: "工数",
  speed: "速度",
  reuse: "再利用性",
  customer_impact: "顧客への影響",
  irreversibility: "不可逆性",
};
export const facts: Record<string, string> = {
  deadline_pressure: "納期の切迫度",
  asset_importance: "資産化の重要度",
  loss_tolerance: "損失の許容度",
  customer_impact: "顧客影響",
  budget_pressure: "予算の厳しさ",
};
export const reasons: Record<string, string> = {
  model_not_independently_validated: "独立した検証が済んでいない候補モデルです",
  missing_information: "判断材料が不足しています",
  conflicting_evidence: "確認済みの記録が競合しています",
  no_matching_confirmed_memory: "同じ条件の確認済み記録がありません",
  advisor_requires_separate_evidence: "助言には別の根拠が必要です",
};
export const examples = [
  {
    domain: "resource_allocation",
    title: "短い納期と、長く使える仕組み。",
    purpose: "来月の顧客向け公開に間に合わせる",
    constraints: "担当者2名・期限4週間・追加予算には限りがある",
    summary:
      "顧客向けの新しい申込機能を4週間で公開する予定です。担当者は2名で、既存サービスの保守も並行しています。外部サービスを使えば短期間で公開できますが、毎月の利用料と運用上の制約が残ります。自社開発は将来の変更に対応しやすい反面、今回の期限には余裕がありません。顧客が必要としているのは基本的な申込と確認の機能です。すべての要望を初回に実現する必要はありません。この架空の条件なら、あなたはどの進め方を選びますか。",
    candidates: [
      "既存サービスを採用して期限内に公開し、運用しながら自社開発の必要性を見極める。",
      "自社で基本機能に絞って開発し、公開後に段階的に機能を追加する。",
      "外部の開発者に依頼し、社内は仕様の整理と受入確認に集中する。",
      "公開時期を調整して、保守しやすい仕組みを自社で丁寧に作る。",
    ],
  },
  {
    domain: "customer_commercial",
    title: "大きな依頼に、どこまで応えるか。",
    purpose: "顧客との関係と既存サービスの品質を守る",
    constraints: "追加対応は2週間・既存顧客への提供予定は維持",
    summary:
      "長く取引している顧客から、個別の運用に合わせた機能の追加依頼が届きました。追加対応には2週間ほど必要です。契約が広がる可能性はありますが、継続利用の確約はまだありません。他の顧客にも使える部分がある一方で、その会社だけの運用に依存する部分もあります。チームは既存サービスの改善を進めており、全てを同時に引き受ける余力はありません。相手の困りごとを解決しながら、長期的に無理のない提供方法を考えたい状況です。この架空の依頼に、どう応えますか。",
    candidates: [
      "複数の顧客に共通する部分に絞って実装し、個別対応の範囲を明確にする。",
      "追加費用と納期を合意したうえで、依頼された個別機能を開発する。",
      "既存機能で代替できる運用を一緒に考え、新しい開発は見送る。",
      "継続利用の条件を先に確認し、見通しが立つまで開発判断を保留する。",
    ],
  },
  {
    domain: "organization_delegation",
    title: "任せることと、見届けること。",
    purpose: "チームの成長と品質を両立する",
    constraints: "新しい担当者・重要な顧客案件・レビュー時間は限定",
    summary:
      "新しい担当者に顧客案件を任せる機会が来ました。本人には関連する経験がありますが、このサービスの運用は初めてです。今回の案件は重要な顧客との最初の取り組みで、品質を落とすことは避けたいと考えています。一方で、すべてを経験者が決めると、担当者が判断する経験を積めません。経験者がレビューできる時間は週に数時間です。顧客への最終的な約束をする前であれば、内容を修正できる余地があります。この架空の状況で、どのように権限を渡しますか。",
    candidates: [
      "目的と判断の基準を共有し、重要な節目だけレビューして日常の判断は任せる。",
      "最初の案件は経験者が並走し、判断の理由を説明しながら段階的に任せる。",
      "担当者に全体を任せ、必要になったときに相談を受ける体制を用意する。",
      "顧客への提案は経験者が担当し、新しい担当者には実行部分から任せる。",
    ],
  },
];

export const policyJa = {
  intro:
    "方針は下書きとして保存し、内容を確認してから本人が承認します。承認済みで有効期間内の方針だけが照合に使われます。",
  staticUnavailable:
    "ブラウザ体験版では判断方針の保存・承認・照合に対応していません。ローカルアプリで利用できます。",
  newPolicy: "新しい方針の下書き",
  statement: "方針の説明",
  statementPlaceholder: "例：納期が厳しいときは、速度を重視する。",
  when: "この背景条件のとき",
  requires: "候補に求める条件",
  threshold: "基準値（0〜1）",
  saveDraft: "下書きを保存",
  draftSaved:
    "方針の下書きを保存しました。内容を確認してから承認してください。",
  draft: "未承認の下書き",
  approved: "承認済み・有効",
  scheduled: "承認済み・開始前",
  expired: "承認済み・期限切れ",
  effective: "適用開始",
  expires: "有効期限（任意）",
  noExpiry: "期限なし",
  now: "保存した時点から",
  approve: "内容を確認して承認",
  acknowledge: "この条件を本人の判断方針として承認します。",
  approvalDone: "方針を承認しました。",
  revoke: "方針を失効・削除",
  revokeConfirm: "この方針を失効し、削除します。以後の照合には使われません。",
  revokeDone: "方針を失効・削除しました。",
  empty: "判断方針はまだありません",
  emptyBody: "適用する背景条件と、候補に求める条件を1つずつ指定できます。",
  readOnly: "保存済みの内容（読み取り専用）",
  check: "いまの背景と候補で方針を照合",
  checkHelp:
    "「育てる・判断する」で開いている背景と候補を使います。記録や回答は変更しません。",
  checks: "方針の照合結果",
  candidate: "候補",
  comparison: "比較",
  details: "内容を確認",
  refresh: "一覧を再読み込み",
  noApproval: "この下書きはまだ照合に使われません。",
  ratioHelp:
    "背景条件は背景の数値、候補条件は候補の数値属性を比較します。値が不明なら違反と決めつけず「不明」と表示します。",
  invalid: "説明、0〜1の基準値、有効期限を確認してください。",
  all: "すべて満たす",
  any: "いずれかを満たす",
  not: "満たさない",
  exists: "値が分かっている",
  included: "いずれかと一致",
  units: "相対値",
  readOnlyHelp: "条件の変更は、新しい下書きを作り直して承認してください。",
};
export const policyComparisons: Record<string, string> = {
  gte: "以上",
  lte: "以下",
  gt: "より大きい",
  lt: "より小さい",
  eq: "と等しい",
};
export const policyResults: Record<string, string> = {
  compliant: "適合",
  violated: "違反",
  unknown: "不明",
  no_applicable_policy: "該当する有効な方針なし",
  not_applicable: "適用条件に該当しない",
};
